- hosts: target
  gather_facts: True
  become: yes

  tasks:
    - name: fast repo settings
      include_tasks: ./fast_repo.yml

    - yum:
        name: httpd
        state: latest

    - systemd:
        name: httpd
        state: started
        enabled: yes

    - template:
        src: index.html.j2
        dest: /var/www/html/index.html
